name: elmed219
dependencies:
- python>=3.6.0
- pip
- ipython
- ipywidgets
- jupyter
- git
- numpy
- matplotlib
- pandas
- scikit-learn>=0.20
- ipykernel
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- conda-forge::statsmodels
- scipy
- seaborn
- pip:
  - pip
  - opencv-python
  - kaggle
  - xgboost
  - graphviz
  - pandas-profiling
  - xlrd
  - nibabel
  - nilearn